line_length:
  warning: 300 
file_length:
  warning: 750 

disabled_rules: 
  - trailing_whitespace 

opt_in_rules: 
  - empty_count
  - contains_over_filter_is_empty

included: 
  - Unsplash Gallery

excluded: 
  - DerivedData
  - Unsplash GalleryUnitTests
